parameters:
    guilro.protection_proxy.access_manager.class: Guilro\ProtectionProxyBundle\AccessManager\AccessManager

services:
    guilro.protection_proxy.access_manager:
        class: %guilro.protection_proxy.access_manager.class%
        arguments:
            parameters:
                protected_classes: %guilro_protection_proxy.access_manager.protected_classes%
            services:
                security.context:   @security.context
